name: C/C++ CI - Meson

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Install meson and ninja
      run: sudo apt-get update && sudo apt-get install -y meson ninja-build
    - name: Configure
      run: meson setup builddir
    - name: Build
      run: meson compile -C builddir
